package org.sisam.langtutor.ui.picture

import org.sisam.langtutor.R

/**
 * Art for the picture vocabulary room, keyed on the vocab WORD — the shape
 * docs/picture-vocabulary.md asks for, so richer art can replace an entry
 * without touching the room.
 *
 * The set covers the picture room's own vocabulary AND the concrete words
 * the phrasebank uses most, because [GlossedText] also stands these icons
 * under words in lines that cannot carry a trustworthy translation.
 *
 * Two tiers, best first: [drawableFor] serves the CURATED set — the flat
 * vector icons drawn by the art queue (one shared style spec, reviewed as a
 * set, converted from SVG by the batch converter; license-clean because they
 * were drawn for this app). [emojiFor] remains the zero-license fallback so
 * a word whose icon hasn't landed yet still gets a card, and so deleting a
 * bad icon can never empty the room.
 *
 * A word with no entry in EITHER map simply does not appear in the room — a
 * card with a missing picture teaches nothing and looks broken.
 */
object PictureArt {

    private val DRAWABLES = mapOf(
        "ant" to R.drawable.pic_ant,
        "apple" to R.drawable.pic_apple,
        "baby" to R.drawable.pic_baby,
        "bag" to R.drawable.pic_bag,
        "ball" to R.drawable.pic_ball,
        "banana" to R.drawable.pic_banana,
        "bath" to R.drawable.pic_bath,
        "beach" to R.drawable.pic_beach,
        "bear" to R.drawable.pic_bear,
        "bed" to R.drawable.pic_bed,
        "bee" to R.drawable.pic_bee,
        "bike" to R.drawable.pic_bike,
        "bird" to R.drawable.pic_bird,
        "block" to R.drawable.pic_block,
        "blue" to R.drawable.pic_blue,
        "boat" to R.drawable.pic_boat,
        "book" to R.drawable.pic_book,
        "bread" to R.drawable.pic_bread,
        "bridge" to R.drawable.pic_bridge,
        "brother" to R.drawable.pic_brother,
        "brush" to R.drawable.pic_brush,
        "bus" to R.drawable.pic_bus,
        "butterfly" to R.drawable.pic_butterfly,
        "button" to R.drawable.pic_button,
        "cake" to R.drawable.pic_cake,
        "camera" to R.drawable.pic_camera,
        "cat" to R.drawable.pic_cat,
        "cereal" to R.drawable.pic_cereal,
        "cheese" to R.drawable.pic_cheese,
        "clock" to R.drawable.pic_clock,
        "cloud" to R.drawable.pic_cloud,
        "coat" to R.drawable.pic_coat,
        "cocoa" to R.drawable.pic_cocoa,
        "computer" to R.drawable.pic_computer,
        "cookie" to R.drawable.pic_cookie,
        "corn" to R.drawable.pic_corn,
        "cow" to R.drawable.pic_cow,
        "crab" to R.drawable.pic_crab,
        "cup" to R.drawable.pic_cup,
        "dad" to R.drawable.pic_dad,
        "dance" to R.drawable.pic_dance,
        "doctor" to R.drawable.pic_doctor,
        "dog" to R.drawable.pic_dog,
        "doll" to R.drawable.pic_doll,
        "door" to R.drawable.pic_door,
        "dough" to R.drawable.pic_dough,
        "drum" to R.drawable.pic_drum,
        "duck" to R.drawable.pic_duck,
        "egg" to R.drawable.pic_egg,
        "elephant" to R.drawable.pic_elephant,
        "eyes" to R.drawable.pic_eyes,
        "feet" to R.drawable.pic_feet,
        "fish" to R.drawable.pic_fish,
        "flower" to R.drawable.pic_flower,
        "forest" to R.drawable.pic_forest,
        "fountain" to R.drawable.pic_fountain,
        "four" to R.drawable.pic_four,
        "friend" to R.drawable.pic_friend,
        "game" to R.drawable.pic_game,
        "garden" to R.drawable.pic_garden,
        "giraffe" to R.drawable.pic_giraffe,
        "goat" to R.drawable.pic_goat,
        "grandma" to R.drawable.pic_grandma,
        "grandpa" to R.drawable.pic_grandpa,
        "guitar" to R.drawable.pic_guitar,
        "hamster" to R.drawable.pic_hamster,
        "hands" to R.drawable.pic_hands,
        "happy" to R.drawable.pic_happy,
        "hat" to R.drawable.pic_hat,
        "head" to R.drawable.pic_head,
        "heart" to R.drawable.pic_heart,
        "honey" to R.drawable.pic_honey,
        "horse" to R.drawable.pic_horse,
        "house" to R.drawable.pic_house,
        "hungry" to R.drawable.pic_hungry,
        "juice" to R.drawable.pic_juice,
        "jump" to R.drawable.pic_jump,
        "kitchen" to R.drawable.pic_kitchen,
        "kite" to R.drawable.pic_kite,
        "ladybug" to R.drawable.pic_ladybug,
        "leaf" to R.drawable.pic_leaf,
        "library" to R.drawable.pic_library,
        "light" to R.drawable.pic_light,
        "lion" to R.drawable.pic_lion,
        "lunch" to R.drawable.pic_lunch,
        "map" to R.drawable.pic_map,
        "milk" to R.drawable.pic_milk,
        "mom" to R.drawable.pic_mom,
        "monkey" to R.drawable.pic_monkey,
        "moon" to R.drawable.pic_moon,
        "mouth" to R.drawable.pic_mouth,
        "nest" to R.drawable.pic_nest,
        "nose" to R.drawable.pic_nose,
        "notebook" to R.drawable.pic_notebook,
        "one" to R.drawable.pic_one,
        "orange" to R.drawable.pic_orange,
        "oven" to R.drawable.pic_oven,
        "pants" to R.drawable.pic_pants,
        "park" to R.drawable.pic_park,
        "parrot" to R.drawable.pic_parrot,
        "party" to R.drawable.pic_party,
        "peach" to R.drawable.pic_peach,
        "pencil" to R.drawable.pic_pencil,
        "penguin" to R.drawable.pic_penguin,
        "phone" to R.drawable.pic_phone,
        "plate" to R.drawable.pic_plate,
        "pot" to R.drawable.pic_pot,
        "puzzle" to R.drawable.pic_puzzle,
        "race" to R.drawable.pic_race,
        "rain" to R.drawable.pic_rain,
        "red" to R.drawable.pic_red,
        "road" to R.drawable.pic_road,
        "rocket" to R.drawable.pic_rocket,
        "room" to R.drawable.pic_room,
        "run" to R.drawable.pic_run,
        "sad" to R.drawable.pic_sad,
        "sand" to R.drawable.pic_sand,
        "sandbox" to R.drawable.pic_sandbox,
        "scared" to R.drawable.pic_scared,
        "screen" to R.drawable.pic_screen,
        "sheep" to R.drawable.pic_sheep,
        "shell" to R.drawable.pic_shell,
        "shirt" to R.drawable.pic_shirt,
        "shoes" to R.drawable.pic_shoes,
        "shop" to R.drawable.pic_shop,
        "sing" to R.drawable.pic_sing,
        "sister" to R.drawable.pic_sister,
        "slide" to R.drawable.pic_slide,
        "snail" to R.drawable.pic_snail,
        "snow" to R.drawable.pic_snow,
        "soap" to R.drawable.pic_soap,
        "socks" to R.drawable.pic_socks,
        "song" to R.drawable.pic_song,
        "soup" to R.drawable.pic_soup,
        "spoon" to R.drawable.pic_spoon,
        "square" to R.drawable.pic_square,
        "squirrel" to R.drawable.pic_squirrel,
        "star" to R.drawable.pic_star,
        "story" to R.drawable.pic_story,
        "strawberry" to R.drawable.pic_strawberry,
        "street" to R.drawable.pic_street,
        "sun" to R.drawable.pic_sun,
        "swim" to R.drawable.pic_swim,
        "swing" to R.drawable.pic_swing,
        "table" to R.drawable.pic_table,
        "tablet" to R.drawable.pic_tablet,
        "teacher" to R.drawable.pic_teacher,
        "teeth" to R.drawable.pic_teeth,
        "telescope" to R.drawable.pic_telescope,
        "tent" to R.drawable.pic_tent,
        "three" to R.drawable.pic_three,
        "timer" to R.drawable.pic_timer,
        "tired" to R.drawable.pic_tired,
        "toast" to R.drawable.pic_toast,
        "towel" to R.drawable.pic_towel,
        "train" to R.drawable.pic_train,
        "tree" to R.drawable.pic_tree,
        "turtle" to R.drawable.pic_turtle,
        "two" to R.drawable.pic_two,
        "umbrella" to R.drawable.pic_umbrella,
        "vegetable" to R.drawable.pic_vegetable,
        "waiter" to R.drawable.pic_waiter,
        "water" to R.drawable.pic_water,
        "watermelon" to R.drawable.pic_watermelon,
        "wind" to R.drawable.pic_wind,
        "window" to R.drawable.pic_window,
        "worm" to R.drawable.pic_worm,
        "yard" to R.drawable.pic_yard,
    )

    fun drawableFor(word: String): Int? = DRAWABLES[word.lowercase()]

    private val EMOJI = mapOf(
        "apple" to "🍎",
        "bag" to "🎒",
        "ball" to "⚽",
        "banana" to "🍌",
        "bear" to "🐻",
        "bird" to "🐦",
        "blue" to "🔵",
        "book" to "📖",
        "bread" to "🍞",
        "brother" to "👦",
        "cat" to "🐱",
        "dance" to "💃",
        "dog" to "🐶",
        "eyes" to "👀",
        "feet" to "🦶",
        "fish" to "🐟",
        "four" to "4️⃣",
        "friend" to "🧑‍🤝‍🧑",
        "grandma" to "👵",
        "grandpa" to "👴",
        "hands" to "🙌",
        "happy" to "😊",
        "hat" to "🎩",
        "head" to "🙂",
        "hungry" to "😋",
        "jump" to "🤸",
        "milk" to "🥛",
        "mom" to "👩",
        "dad" to "👨",
        "mouth" to "👄",
        "nose" to "👃",
        "one" to "1️⃣",
        "pants" to "👖",
        "pencil" to "✏️",
        "red" to "🔴",
        "run" to "🏃",
        "sad" to "😢",
        "scared" to "😨",
        "shirt" to "👕",
        "shoes" to "👟",
        "sing" to "🎤",
        "sister" to "👧",
        "socks" to "🧦",
        "swim" to "🏊",
        "teacher" to "🧑‍🏫",
        "three" to "3️⃣",
        "tired" to "😴",
        "two" to "2️⃣",
    )

    fun emojiFor(word: String): String? = EMOJI[word.lowercase()]
}
