package org.sisam.langtutor.speech

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin Phonikud port to the Python reference: every vector in
 * src/test/resources/phonikud was generated by the reference implementation
 * (rules with expander off; nikud arrays by the REAL int8 ONNX model), so a
 * pass here means byte-level parity on the covered pipeline.
 */
class PhonikudPhonemizerTest {

    private fun resource(name: String) =
        checkNotNull(javaClass.classLoader.getResourceAsStream(name)) { "$name missing" }
            .bufferedReader(Charsets.UTF_8)

    @Test
    fun `pointed-text goldens match the reference phonemizer byte for byte`() {
        var cases = 0
        resource("phonikud/goldens.tsv").useLines { lines ->
            for (line in lines) {
                if (line.isBlank()) continue
                val (pointed, expected) = line.split('\t', limit = 2)
                assertEquals("for input: $pointed", expected, PhonikudPhonemizer.phonemize(pointed))
                cases++
            }
        }
        assertTrue("suspiciously few golden cases: $cases", cases >= 12)
    }

    @Test
    fun `restorer plus phonemizer reproduce the reference on real model outputs`() {
        val blocks = resource("phonikud/restorer-fixture.txt").readText()
            .split("\n\n").filter { it.isNotBlank() }
        assertTrue(blocks.size >= 2)
        for (block in blocks) {
            val f = block.lines().filter { it.isNotBlank() }
                .associate { it.substringBefore('\t') to it.substringAfter('\t') }
            val text = f.getValue("TEXT")
            fun ints(k: String) = f.getValue(k).split(' ').map { it.toInt() }
            fun bools(k: String) = ints(k).map { it == 1 }.toBooleanArray()

            // Our per-char tokenizer must match the ids the model was fed with.
            val tokenizer = DictaTokenizer.load()
            assertArrayEquals(
                "tokenizer ids for: $text",
                ints("IDS").map { it.toLong() }.toLongArray(),
                tokenizer.encode(text),
            )

            val pointed = NikudRestorer.restore(
                text = text,
                nikudClass = ints("NIKUD").toIntArray(),
                shinClass = ints("SHIN").toIntArray(),
                stress = bools("STRESS"),
                vocalShva = bools("SHVA"),
                prefix = bools("PREFIX"),
            )
            assertEquals("pointed for: $text", f.getValue("POINTED"), pointed)
            assertEquals("phonemes for: $text", f.getValue("PHONEMES"), PhonikudPhonemizer.phonemize(pointed))
        }
    }

    @Test
    fun `piper id encoding matches the validated reference sequence`() {
        val (phonemes, idsStr) = resource("phonikud/piper-golden.tsv").readLine().split('\t')
        val expected = idsStr.split(' ').map { it.toLong() }.toLongArray()
        assertArrayEquals(expected, PiperPhonemes.toIds(phonemes))
    }

    @Test
    fun `removeNikud strips points and phonikud marks`() {
        assertEquals("שלום", NikudRestorer.removeNikud("שָׁל֫וֹם"))
        assertEquals("ביחד", NikudRestorer.removeNikud("בְּֽיַחַד"))
    }
}
