package org.sisam.langtutor.speech

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins the Kotlin Phonikud port to the Python reference: every vector in
 * src/test/resources/phonikud was generated by the reference implementation
 * (rules with expander off; nikud arrays by the REAL int8 ONNX model), so a
 * pass here means byte-level parity on the covered pipeline.
 */
class PhonikudPhonemizerTest {

    private fun resource(name: String) =
        checkNotNull(javaClass.classLoader.getResourceAsStream(name)) { "$name missing" }
            .bufferedReader(Charsets.UTF_8)

    @Test
    fun `pointed-text goldens match the reference phonemizer byte for byte`() {
        var cases = 0
        resource("phonikud/goldens.tsv").useLines { lines ->
            for (line in lines) {
                if (line.isBlank()) continue
                val (pointed, expected) = line.split('\t', limit = 2)
                assertEquals("for input: $pointed", expected, PhonikudPhonemizer.phonemize(pointed))
                cases++
            }
        }
        assertTrue("suspiciously few golden cases: $cases", cases >= 12)
    }

    @Test
    fun `restorer plus phonemizer reproduce the reference on real model outputs`() {
        val blocks = resource("phonikud/restorer-fixture.txt").readText()
            .split("\n\n").filter { it.isNotBlank() }
        assertTrue(blocks.size >= 2)
        for (block in blocks) {
            val f = block.lines().filter { it.isNotBlank() }
                .associate { it.substringBefore('\t') to it.substringAfter('\t') }
            val text = f.getValue("TEXT")
            fun ints(k: String) = f.getValue(k).split(' ').map { it.toInt() }
            fun bools(k: String) = ints(k).map { it == 1 }.toBooleanArray()

            // Our per-char tokenizer must match the ids the model was fed with.
            val tokenizer = DictaTokenizer.load()
            assertArrayEquals(
                "tokenizer ids for: $text",
                ints("IDS").map { it.toLong() }.toLongArray(),
                tokenizer.encode(text),
            )

            val pointed = NikudRestorer.restore(
                text = text,
                nikudClass = ints("NIKUD").toIntArray(),
                shinClass = ints("SHIN").toIntArray(),
                stress = bools("STRESS"),
                vocalShva = bools("SHVA"),
                prefix = bools("PREFIX"),
            )
            assertEquals("pointed for: $text", f.getValue("POINTED"), pointed)
            assertEquals("phonemes for: $text", f.getValue("PHONEMES"), PhonikudPhonemizer.phonemize(pointed))
        }
    }

    /**
     * The whole Hebrew-voice integration rests on this: Kokoro's Hebrew export
     * ships a vocabulary byte-identical to the English one, and Phonikud
     * already normalises its output to exactly those symbols (ɡ, χ, ʁ — not
     * ASCII g, x, r). So there is no Hebrew tokenizer and no mapping layer.
     *
     * [KokoroPhonemizer.encode] drops unrecognised symbols SILENTLY, so a
     * front end that drifted out of that alphabet would not fail — it would
     * quietly lose phonemes and just sound wrong. This is the assertion that
     * makes the shared encoder safe to rely on.
     */
    @Test
    fun `every phoneme Phonikud emits is carried by the Kokoro vocabulary`() {
        val kokoro = KokoroPhonemizer.load()
        var cases = 0
        resource("phonikud/goldens.tsv").useLines { lines ->
            for (line in lines) {
                if (line.isBlank()) continue
                val expected = line.split('\t', limit = 2)[1]
                assertEquals(
                    "Kokoro cannot encode these symbols from: $expected",
                    emptySet<Char>(),
                    kokoro.unsupported(expected),
                )
                assertTrue("nothing encoded for: $expected", kokoro.encode(expected).isNotEmpty())
                cases++
            }
        }
        assertTrue("suspiciously few cases: $cases", cases >= 12)
    }

    @Test
    fun `hebrew number words match the reference for EVERY value 0-999`() {
        var cases = 0
        resource("phonikud/number-goldens.tsv").useLines { lines ->
            for (line in lines) {
                if (line.isBlank()) continue
                val (n, bare, pointed) = line.split('\t', limit = 3)
                assertEquals("bare for $n", bare, HebrewNumbers.bareWords(n.toInt()))
                assertEquals("pointed for $n", pointed, HebrewNumbers.toPointedWords(n.toInt()))
                cases++
            }
        }
        assertEquals(1000, cases)
        assertEquals(null, HebrewNumbers.toPointedWords(1000))
    }

    @Test
    fun `removeNikud strips points and phonikud marks`() {
        assertEquals("שלום", NikudRestorer.removeNikud("שָׁל֫וֹם"))
        assertEquals("ביחד", NikudRestorer.removeNikud("בְּֽיַחַד"))
    }
}
