package org.sisam.langtutor.speech

import kotlin.math.cos
import kotlin.math.log10
import kotlin.math.max
import kotlin.math.min
import org.jtransforms.fft.FloatFFT_1D

/**
 * Whisper audio frontend, pure JVM: 16 kHz mono PCM -> the 80x3000 log-mel
 * spectrogram the Whisper encoder expects. Mirrors the canonical preprocessing
 * (OpenAI / HF WhisperFeatureExtractor) exactly:
 *
 *   pad/truncate to 30 s -> centered STFT (n_fft 400, hop 160, periodic Hann,
 *   reflect padding) -> power spectrum -> 80-bin slaney-scale/slaney-norm mel
 *   filterbank (0..8 kHz) -> log10 -> floor at global max - 8 -> (x + 4) / 4
 *
 * Verified against golden vectors generated by the reference implementation
 * (WhisperFrontendTest) — this is the part of the bundled-ASR plan where a
 * silent numeric bug would corrupt every transcription, so it is the part
 * that is unit-tested hardest. Runs anywhere (no Android APIs): the on-device
 * WhisperAsrEngine feeds AudioRecord PCM in; tests feed synthetic signals.
 */
object WhisperFrontend {

    const val SAMPLE_RATE = 16_000
    const val N_FFT = 400
    const val HOP = 160
    const val N_MELS = 80
    const val N_FRAMES = 3000
    private const val N_SAMPLES = SAMPLE_RATE * 30
    private const val N_FREQS = N_FFT / 2 + 1 // 201
    private const val FMAX = 8000.0

    private val hann = FloatArray(N_FFT) { i ->
        (0.5 - 0.5 * cos(2.0 * Math.PI * i / N_FFT)).toFloat() // periodic Hann
    }

    /** [N_MELS][N_FREQS] slaney-scale, slaney-normalized triangular filters. */
    private val melFilters: Array<FloatArray> = buildMelFilters()

    /** @param pcm 16 kHz mono in [-1, 1]; longer than 30 s is truncated. */
    fun logMel(pcm: FloatArray): Array<FloatArray> {
        // 1) pad/truncate to exactly 30 s, then reflect-pad n_fft/2 both ends.
        val padded = FloatArray(N_SAMPLES + N_FFT) // N_FFT/2 margin each side
        val n = min(pcm.size, N_SAMPLES)
        System.arraycopy(pcm, 0, padded, N_FFT / 2, n)
        for (i in 0 until N_FFT / 2) {
            padded[N_FFT / 2 - 1 - i] = padded[N_FFT / 2 + 1 + i] // left reflect
            padded[N_FFT / 2 + N_SAMPLES + i] = padded[N_FFT / 2 + N_SAMPLES - 2 - i]
        }

        // 2) centered STFT -> mel power, frame by frame.
        val fft = FloatFFT_1D(N_FFT.toLong())
        val frame = FloatArray(N_FFT)
        val power = FloatArray(N_FREQS)
        val mel = Array(N_MELS) { FloatArray(N_FRAMES) }
        for (t in 0 until N_FRAMES) {
            val start = t * HOP
            for (i in 0 until N_FFT) frame[i] = padded[start + i] * hann[i]
            fft.realForward(frame)
            // JTransforms even-n packing: [Re0, Re(n/2), Re1, Im1, Re2, Im2, ...]
            power[0] = frame[0] * frame[0]
            power[N_FREQS - 1] = frame[1] * frame[1]
            for (k in 1 until N_FFT / 2) {
                val re = frame[2 * k]
                val im = frame[2 * k + 1]
                power[k] = re * re + im * im
            }
            for (m in 0 until N_MELS) {
                val filt = melFilters[m]
                var acc = 0.0f
                for (k in 0 until N_FREQS) acc += filt[k] * power[k]
                mel[m][t] = acc
            }
        }

        // 3) log10 with floor, then Whisper's global-max normalization.
        var globalMax = Float.NEGATIVE_INFINITY
        for (m in 0 until N_MELS) for (t in 0 until N_FRAMES) {
            val v = log10(max(mel[m][t], 1e-10f).toDouble()).toFloat()
            mel[m][t] = v
            if (v > globalMax) globalMax = v
        }
        val floor = globalMax - 8.0f
        for (m in 0 until N_MELS) for (t in 0 until N_FRAMES) {
            mel[m][t] = (max(mel[m][t], floor) + 4.0f) / 4.0f
        }
        return mel
    }

    // ---- slaney mel scale (librosa defaults, htk=false, norm='slaney') ----

    private fun hzToMel(hz: Double): Double {
        val fSp = 200.0 / 3
        val minLogHz = 1000.0
        val minLogMel = minLogHz / fSp
        val logstep = Math.log(6.4) / 27.0
        return if (hz < minLogHz) hz / fSp else minLogMel + Math.log(hz / minLogHz) / logstep
    }

    private fun melToHz(mel: Double): Double {
        val fSp = 200.0 / 3
        val minLogHz = 1000.0
        val minLogMel = minLogHz / fSp
        val logstep = Math.log(6.4) / 27.0
        return if (mel < minLogMel) mel * fSp else minLogHz * Math.exp(logstep * (mel - minLogMel))
    }

    private fun buildMelFilters(): Array<FloatArray> {
        val fftFreqs = DoubleArray(N_FREQS) { it * SAMPLE_RATE.toDouble() / N_FFT }
        val melMin = hzToMel(0.0)
        val melMax = hzToMel(FMAX)
        val melPoints = DoubleArray(N_MELS + 2) { melMin + (melMax - melMin) * it / (N_MELS + 1) }
        val hzPoints = DoubleArray(N_MELS + 2) { melToHz(melPoints[it]) }
        return Array(N_MELS) { m ->
            val lower = hzPoints[m]
            val center = hzPoints[m + 1]
            val upper = hzPoints[m + 2]
            val norm = 2.0 / (upper - lower) // slaney normalization
            FloatArray(N_FREQS) { k ->
                val f = fftFreqs[k]
                val up = (f - lower) / (center - lower)
                val down = (upper - f) / (upper - center)
                (max(0.0, min(up, down)) * norm).toFloat()
            }
        }
    }
}
